version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpassword
        POSTGRES_DB: testtaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: testtaskdb
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data:
